FROM eclipse-temurin:17 as builder

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN chmod +x ./gradlew
RUN ./gradlew clean bootJar
RUN ./gradlew bootJar

FROM eclipse-temurin:17

ARG ARG_DATASOURCE_URL
ARG ARG_DATASOURCE_USERNAME
ARG ARG_DATASOURCE_PASSWORD
ARG ARG_JPA_DIALECT
ARG ARG_DDLAUTO
ARG ARG_DRIVE_CLASS_NAME
ARG ARG_CLUSTER_ENDPOINT
ARG ARG_COLLECTION_NAME
ARG ARG_OPEN_AI_URL
ARG ARG_OPEN_AI_EMBEDDING_URL
ARG ARG_OPEN_AI_KEY

ENV SPRING_DATASOURCE_DRIVERCLASSNAME=${ARG_DRIVE_CLASS_NAME}
ENV SPRING_DATASOURCE_URL=${ARG_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${ARG_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${ARG_DATABASE_PASSWORD}
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${ARG_JPA_DIALECT}
ENV SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=${ARG_DDLAUTO}
ENV SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
ENV SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=false

ENV CLUSTER_ENDPOINT=${ARG_CLUSTER_ENDPOINT}
ENV COLLECTION_NAME=${ARG_COLLECTION_NAME}

ENV OPEN_AI_URL=${OPEN_AI_URL}
ENV OPEN_AI_EMBEDDING_URL=${OPEN_AI_EMBEDDING_URL}

COPY --from=builder build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app.jar"]